### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by justin2004** [HL7/v2-to-fhir#39]
hello,

how would someone use this project?

the .fsh files seem to specify mappings from hl7v2 segments/fields/components (maybe?) to fhir fields -- is that correct?

if so how does one actually carry out a mapping from a hl7v2 message (in bar-hat form) to a fhir representation (in jsonld or turtle serialization)?

**Comment by hbuitendijk** [comment]
The actual mappings (automated or manual)) would have to be performed by the implementer  These mappings only define the mappings, not execute the mappings.

Hans J. Buitendijk, M.Sc., FHL7 | Director, Interoperability Strategy | ***@***.******@***.***> | +1 610-219-2087 office/mobile | Cerner Corporation | www.cerner.com<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cerner.com%2F&data=02%7C01%7CHans.Buitendijk%40Cerner.com%7C46a83a5d4bb64fa0dc5d08d6980ea693%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C636863586028303617&sdata=OJQaj00RbusXrzTqEghLpDT1vCRhiA2bVi3oN59Km14%3D&reserved=0>

From: justin2004 ***@***.***>
Sent: Saturday, April 17, 2021 09:28
To: HL7/v2-to-fhir ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HL7/v2-to-fhir] usage question (#39)


hello,

how would someone use this project?

the .fsh files seem to specify mapping from hl7v2 segments/fields/components (maybe?) to fhir fields -- is that correct?

if so how does one actually carry out a mapping from a hl7v2 message to a fhir representation (in jsonld or turtle serialization)?

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHL7%2Fv2-to-fhir%2Fissues%2F39&data=04%7C01%7Chans.buitendijk%40cerner.com%7C438aa2e21cfd4513bb1d08d901a4a4c5%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637542628951012469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Slx%2BkWaoTE0etLolQVualnwFWJMZnQSi1wrZwP3cR14%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEEBFLEJHNKUELNAS4FTIN3TJGEGTANCNFSM43DCPYDA&data=04%7C01%7Chans.buitendijk%40cerner.com%7C438aa2e21cfd4513bb1d08d901a4a4c5%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637542628951022465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nbW4qT4kDxJChH5upP%2FGalDcn65qhxhHxrUswgBc3B0%3D&reserved=0>.



CONFIDENTIALITY NOTICE This message and any included attachments are from Cerner Corporation and are intended only for the addressee. The information contained in this message is confidential and may constitute inside or non-public information under international, federal, or state securities laws. Unauthorized forwarding, printing, copying, distribution, or use of such information is strictly prohibited and may be unlawful. If you are not the addressee, please promptly delete this message and notify the sender of the delivery error by e-mail or you may call Cerner's corporate offices in Kansas City, Missouri, U.S.A at (+1) (816)221-1024.

**Comment by justin2004** [comment]
thanks for the clarification.
